language: python
python:
  - 3.7
stages:
  - name: deploy
    if: branch = master
script:
  - "./sanity-tests.sh ${TRAVIS_PYTHON_VERSION}"
  - "rm -rf ansible_collections/spam_n_eggs_amazon/tests/output"
before_deploy:
  - "ansible-galaxy collection build ansible_collections/spam_n_eggs/amazon"
deploy:
  - "ansible-galaxy collection publish --api-key ${ANSIBLE_API_KEY} *.tar.gz"