language: python
python:
  - 3.7
stages:
  - name: deploy
    if: branch = master
script:
  - "./sanity-tests.sh ${TRAVIS_PYTHON_VERSION}"
before_deploy:
  - "rm -rf ansible_collections/tapp/amazon/tests/output"
  - "ansible-galaxy collection build ansible_collections/tapp/amazon"
deploy:
  skip_cleanup: true
  provider: script
  script: "ansible-galaxy collection publish --api-key ${ANSIBLE_API_KEY} $(find *.tar.gz)"
